CREATE DATABASE QuanlySV;
USE QuanlySV;

CREATE TABLE KHOA(
	MASO VARCHAR(10) NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	NAMTHANHLAP INT NOT NULL
);

ALTER TABLE KHOA ADD CONSTRAINT PK_MASO1 PRIMARY KEY(MASO);

CREATE TABLE SINHVIEN(
	TENSV NVARCHAR(50) NOT NULL,
	MASV VARCHAR(10) NOT NULL,
	NAMSINH INT NOT NULL,
	MAKHOA VARCHAR(10) NOT NULL
);

ALTER TABLE SINHVIEN ADD CONSTRAINT PK_MASV1 PRIMARY KEY(MASV);
ALTER TABLE sinhvien add constraint FK_MAKHOA1 foreign key(makhoa) references khoa(MASO);

CREATE TABLE MONHOC(
	TENMH NVARCHAR(50) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	TINCHI INT NOT NULL,
	MAKHOA VARCHAR(10) NOT NULL
);

ALTER TABLE MONHOC ADD CONSTRAINT PK_MAMH1 PRIMARY KEY(MAMH);
ALTER TABLE MONHOC ADD CONSTRAINT FK_MAKHOA2 FOREIGN KEY(MAKHOA) REFERENCES KHOA(MASO);

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL
);

ALTER TABLE DIEUKIEN ADD CONSTRAINT PK_MAMH_MAMH_TRUOC1 PRIMARY KEY(MAMH, MAMH_TRUOC);
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MAMH1 FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MAMH2 FOREIGN KEY(MAMH_TRUOC) REFERENCES MONHOC(MAMH);

CREATE TABLE HOCPHAN(
	MAHP VARCHAR(10) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	HOCKY VARCHAR(1) NOT NULL,
	NAM INT NOT NULL,
	GIAOVIEN NVARCHAR(50) NOT NULL
);

ALTER TABLE HOCPHAN ADD CONSTRAINT PK_MAHP1 PRIMARY KEY(MAHP);
ALTER TABLE HOCPHAN ADD CONSTRAINT FK_MAMH3 FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

CREATE TABLE KETQUA(
	MASV VARCHAR(10) NOT NULL,
	MAHP VARCHAR(10) NOT NULL,
	DIEM VARCHAR(1) NOT NULL
);

ALTER TABLE KETQUA ADD CONSTRAINT PK_MASV2_MAHP2 PRIMARY KEY(MASV, MAHP);
ALTER TABLE KETQUA ADD CONSTRAINT FK_MAHP1 FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP);
ALTER TABLE KETQUA ADD CONSTRAINT FK_MASV1 FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV);

INSERT INTO KHOA values (501, 'CNTT', 2007);
INSERT INTO KHOA values (502, 'QTKD', 1983);
INSERT INTO KHOA values (503, 'Đ-ĐT', 2001);

INSERT INTO sinhvien values ('Nguyễn Đình Việt Hoàng', 'SV001', 2004, 501);
INSERT INTO sinhvien values ('Nguyễn Thị Hồng Thắm', 'SV002', 2004, 503);
INSERT INTO sinhvien values ('Lương Đình Anh Khoa', 'SV003', 2003, 502);

INSERT INTO MONHOC values ('Hệ cơ sở dữ liệu', 'HCSDL', 4, 501);
INSERT INTO MONHOC values ('Phương pháp lập trình', 'PPLT', 4, 501);
INSERT INTO MONHOC values ('Quan hệ công chúng', 'QHCC', 3, 502);

INSERT INTO DIEUKIEN values ('HCSDL', 'QHCC');

INSERT INTO HOCPHAN values (502102, 'HCSDL', 1, 2022, 'Lương Thị Ngọc Khánh');
INSERT INTO HOCPHAN values (502103, 'QHCC', 2, 2023, 'Doãn Xuân Thanh');
INSERT INTO HOCPHAN values (502104, 'HCSDL', 3, 2021, 'Nguyễn Thế Hữu');

INSERT INTO KETQUA values ('SV001', 502102, 9);
INSERT INTO KETQUA values ('SV001', 502103, 10);
INSERT INTO KETQUA values ('SV003', 502103, 10);