--BAI_1
--CAU1
CREATE DATABASE Quanlysinhvien;
USE Quanlysinhvien;

CREATE TABLE KHOA(
	MAKHOA VARCHAR(10) NOT NULL,
	TENKHOA VARCHAR(50) NOT NULL
);

ALTER TABLE KHOA ADD CONSTRAINT PK_MAKHOA1 PRIMARY KEY(MAKHOA);

CREATE TABLE SINHVIEN(
	HOSV VARCHAR(50) NOT NULL,
	TENSV VARCHAR(50) NOT NULL,
	MASV VARCHAR(10) NOT NULL,
	PHAI VARCHAR(10) NOT NULL,
	NAMSINH SMALLDATETIME NOT NULL,
	MAKHOA VARCHAR(10) NOT NULL
);

ALTER TABLE SINHVIEN ADD CONSTRAINT PK_MASV1 PRIMARY KEY(MASV);
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_MAKHOA1 FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA);


CREATE TABLE MONHOC(
	TENMH VARCHAR(50) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	SOTIET INT NOT NULL
);

ALTER TABLE MONHOC ADD CONSTRAINT PK_MAMH1 PRIMARY KEY(MAMH);

CREATE TABLE KETQUA(
	MASV VARCHAR(10) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	LANTHI SMALLINT NOT NULL,
	DIEM SMALLINT NOT NULL
);

ALTER TABLE KETQUA ADD CONSTRAINT PK_MASV2_MAMH2_LANTHI1 PRIMARY KEY(MASV, MAMH, LANTHI);
ALTER TABLE KETQUA ADD CONSTRAINT FK_MASV1 FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV);
ALTER TABLE KETQUA ADD CONSTRAINT FK_MAMH1 FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

--CAU2
ALTER TABLE KETQUA DROP CONSTRAINT FK_MASV1;
ALTER TABLE KETQUA DROP CONSTRAINT FK_MAMH1;
ALTER TABLE SINHVIEN DROP CONSTRAINT FK_MAKHOA1;

--CAU3
DROP TABLE KHOA;
DROP TABLE MONHOC;
DROP TABLE SINHVIEN;
DROP TABLE KETQUA;

--CAU4
ALTER TABLE KETQUA ADD CONSTRAINT FK_MASV1 FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV);
ALTER TABLE KETQUA ADD CONSTRAINT FK_MAMH1 FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

CREATE TABLE KHOA(
	MAKHOA VARCHAR(10) NOT NULL,
	TENKHOA VARCHAR(50) NOT NULL,
);

ALTER TABLE KHOA ADD CONSTRAINT PK_MAKHOA1 PRIMARY KEY(MAKHOA);

CREATE TABLE MONHOC(
	TENMH VARCHAR(50) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	SOTIET INT NOT NULL
);

ALTER TABLE MONHOC ADD CONSTRAINT PK_MAMH1 PRIMARY KEY(MAMH);
--CAU5
INSERT INTO KHOA VALUES('AVAN', 'Khoa anh Van'), ('CNTT', 'Cong Nghe Thong Tin'), ('DTVT', 'Dien Tu Vien Thong'), ('QTKD', 'Quan Tri Kinh Doanh');
INSERT INTO SINHVIEN VALUES('Tran Minh', 'Son', 'S001', 'Nam', '05/01/1985', 'CNTT'), ('Nguyen Quoc', 'Bao', 'S002', 'Nam', '06/15/1986', 'CNTT'), ('Phan Anh', 'Tung', 'S003', 'Nam', '12/20/1983', 'QTKD'), ('Bui Thi anh', 'Thu', 'S004', 'Nu', '02/01/1985', 'QTKD'), ('Le Thi Lan', 'Anh', 'S005', 'Nu', '07/03/1987', 'DTVT'), ('Nguyen Thi', 'Lam', 'S006', 'Nu','11/25/1984', 'DTVT'), ('Phan Thi', 'Ha', 'S007', 'Nu', '07/03/1988', 'CNTT'), ('Tran The', 'Dung', 'S008', 'Nam', '10/21/1985', 'CNTT');
INSERT INTO MONHOC VALUES('Anh Van', 'AV', '45'), ('Co So Du Lieu', 'CSDL', '45'), ('Ky Thuat Lap Trinh', 'KTLT', '60'), ('Ke Toan Tai Chinh', 'KTTC', '45'), ('Toan Cao Cap', 'TCC', '60'), ('Tin Hoc Van Phong', 'THVP', '30'), ('Tri Tue Nhan Tao', 'TTNT', '45');
INSERT INTO KETQUA VALUES('S001', 'CSDL', '1', '4'), ('S001', 'TCC', '1', '6'), ('S002', 'CSDL', '1', '3'), ('S002', 'CSDL', '2', '6'), ('S003', 'KTTC', '1', '5'), ('S004', 'AV', '1', '8'), ('S004', 'THVP', '1', '4'), ('S004', 'THVP', '2', '8'), ('S006', 'TCC', '1', '5'), ('S007', 'AV', '1', '2'), ('S007', 'AV', '2', '9'), ('S007', 'KTLT', '1', '6'), ('S008', 'AV', '1', '7');
SELECT * FROM KHOA;
SELECT * FROM SINHVIEN;
SELECT * FROM MONHOC;
SELECT * FROM KETQUA;

--CAU6
UPDATE MONHOC 
SET SOTIET = 30
WHERE MAMH = 'TTNT';

--CAU7
DELETE FROM KETQUA
WHERE MASV = 'S001';

--CAU8
INSERT INTO KETQUA VALUES ('S001', 'CSDL', '1', '4'), ('S001', 'TCC', '1', '6');

--CAU9
UPDATE SINHVIEN
SET HOSV = 'Nguyen Van', TENSV = 'Lam', PHAI = 'Nam' WHERE HOSV = 'Nguyen Thi' AND TENSV = 'Lam';

--CAU10
UPDATE SINHVIEN
SET MAKHOA = 'CNTT' WHERE HOSV = 'Le Thi Lan' and TENSV = 'Anh';

--BAI_2
--CAU1
CREATE DATABASE Quanlybanhang;
USE Quanlybanhang;

CREATE TABLE KHACHHANG(
	MAKHACHHANG VARCHAR(20) NOT NULL,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL
);
ALTER TABLE KHACHHANG ADD CONSTRAINT PK_MAKHACHHANG1 PRIMARY KEY(MAKHACHHANG);

CREATE TABLE NHANVIEN(
	MANHANVIEN VARCHAR(20) NOT NULL,
	HO NVARCHAR(100) NOT NULL,
	TEN NVARCHAR(100) NOT NULL,
	NGAYSINH SMALLDATETIME NOT NULL,
	NGAYLAMVIEC SMALLDATETIME NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	LUONGCOBAN VARCHAR(20) NOT NULL,
	PHUCAP VARCHAR(20) NOT NULL
);
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_MANHANVIEN1 PRIMARY KEY(MANHANVIEN);

CREATE TABLE NHACUNGCAP(
	MACONGTY VARCHAR(20) NOT NULL,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
);
ALTER TABLE NHACUNGCAP ADD CONSTRAINT PK_MACONGTY1 PRIMARY KEY(MACONGTY);

CREATE TABLE LOAIHANG(
	MALOAIHANG VARCHAR(20) NOT NULL,
	TENLOAIHANG NVARCHAR(100) NOT NULL
);
ALTER TABLE LOAIHANG ADD CONSTRAINT PK_MALOAIHANG1 PRIMARY KEY(MALOAIHANG);

CREATE TABLE DONDATHANG(
	SOHOADON VARCHAR(20) NOT NULL,
	MAKHACHHANG VARCHAR(20) NOT NULL,
	MANHANVIEN VARCHAR(20) NOT NULL,
	NGAYDATHANG SMALLDATETIME NOT NULL,
	NGAYGIAOHANG SMALLDATETIME NOT NULL,
	NGAYCHUYENHANG SMALLDATETIME NOT NULL,
	NOIGIAOHANG NVARCHAR(100) NOT NULL
);
ALTER TABLE DONDATHANG ADD CONSTRAINT PK_SOHOADON1 PRIMARY KEY(SOHOADON);
ALTER TABLE DONDATHANG ADD CONSTRAINT FK_MAKHACHHANG1 FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE DONDATHANG ADD CONSTRAINT FK_MANHANVIEN1 FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

CREATE TABLE MATHANG(
	MAHANG VARCHAR(20) NOT NULL,
	TENHANG NVARCHAR(100) NOT NULL,
	MACONGTY VARCHAR(20) NOT NULL,
	MALOAIHANG VARCHAR(20) NOT NULL,
	SOLUONG INT NOT NULL,
	DONVITINH NVARCHAR(20) NOT NULL,
	GIAHANG INT NOT NULL
);
ALTER TABLE MATHANG ADD CONSTRAINT PK_MAHANG1 PRIMARY KEY(MAHANG);
ALTER TABLE MATHANG ADD CONSTRAINT FK_MACONGTY1 FOREIGN KEY(MACONGTY) REFERENCES NHACUNGCAP(MACONGTY);
ALTER TABLE MATHANG ADD CONSTRAINT FK_MALOAIHANG1 FOREIGN KEY(MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG);

CREATE TABLE CHITIETDATHANG(
	SOHOADON VARCHAR(20) NOT NULL,
	MAHANG VARCHAR(20) NOT NULL,
	GIABAN INT NOT NULL,
	SOLUONG INT NOT NULL,
	MUCGIAMGIA INT NOT NULL
);
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT PK_SOHOADON2_MAHANG2 PRIMARY KEY(SOHOADON, MAHANG);
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT FK_MAHANG1 FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG);
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT FK_SOHOADON1 FOREIGN KEY(SOHOADON) REFERENCES DONDATHANG(SOHOADON);

SELECT * FROM KHACHHANG;
SELECT * FROM NHANVIEN;
SELECT * FROM NHACUNGCAP;
SELECT * FROM LOAIHANG;
SELECT * FROM DONDATHANG;
SELECT * FROM MATHANG;
SELECT * FROM CHITIETDATHANG;

--CAU2
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT DEFAULT_SOLUONG1 DEFAULT 1 FOR SOLUONG;
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT DEFAULT_MUCGIAMGIA1 DEFAULT 0 FOR MUCGIAMGIA;

--CAU3
ALTER TABLE DONDATHANG ADD CONSTRAINT CHECK_NGAYGIAOHANG1_NGAYCHUYENHANG1 CHECK(NGAYGIAOHANG >= NGAYDATHANG AND NGAYCHUYENHANG >= NGAYDATHANG);

--CAU4
ALTER TABLE NHANVIEN ADD CONSTRAINT CHECK_SOTUOI1 CHECK(YEAR(NGAYLAMVIEC) - YEAR(NGAYSINH) >= 18 AND YEAR(NGAYLAMVIEC) - YEAR(NGAYSINH) <= 60);

--CAU5
--KHONG THE DROP TABLE NHACUNGCAP VI TABLE MATHANG THAM CHIEU KHOA NGOAI DEN TABLE NHACUNGCAP
--BAI_3